### PR TITLE
Add a nil check on querySelector for title

### LINKED ISSUE #3: Cannot read property 'textContent' of null
**Describe the bug**

```
TypeError: Cannot read property 'textContent' of null
    at module.exports.getMarkdownFromPost (/Users/param/.npm/_npx/16523/lib/node_modules/medium-to-own-blog/generate-md.js:182:58)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

**Screenshots**
Screenshot 2019-05-31 at 11 39 16 PM

### PR DESCRIPTION
**Pull request by paramaggarwal**
fixes #3

### CODE REVIEW

**Comment by mathieudutour** [comment]
Does it really fix the issue? It's weird that an article doesn't have a title 🤔

**Comment by paramaggarwal** [comment]
An article won't have a title when it is actually a response to another post on Medium. Note that when you 'comment' on an article, it is treated as a response article by Medium.

I just imported my 126 posts from Medium after this change. It does fix the issue.

**Comment by mathieudutour** [comment]
> Note that when you 'comment' on an article, it is treated as a response article by Medium.

It is indeed but it doesn't have any tags so I'm filtering them out: https://github.com/mathieudutour/medium-to-own-blog/blob/master/generate-md.js#L182-L185

Maybe we should do the same for article that are a response to another post? Is there any case where you'd want to keep a response?

**Comment by paramaggarwal** [comment]
Oh I didn't release you were filtering them out. In that case it appears that I have a post that does not have a title. This is definitely possible as a title is not mandatory when creating a Medium post.

**Comment by mathieudutour** [comment]
> This is definitely possible as a title is not mandatory when creating a Medium post.

Really? Do you have an example of such post? I'd like to see if we can pick something as the title

**Comment by paramaggarwal** [comment]
[Here](https://medium.com/@paramaggarwal/i-had-written-a-letter-to-chip-magazine-regarding-reviewing-higher-end-devices-like-mac-and-ipod-308d7758aedb) is an example of an article I have that does not have a title.

**Comment by mathieudutour** [comment]
Perfect thanks!

Took a bit of a different approach here: https://github.com/mathieudutour/medium-to-own-blog/commit/614426785442927ea26312a35bf347d81a5cc0d5

**Comment by paramaggarwal** [comment]
Your approach is much cleaner.

I am inspired by your level of attention to detail - it also shines though in the experience of using your tool. Thanks!

**Comment by mathieudutour** [comment]
Thanks, really appreciated 🙏

**Pull request closed without merging**
