### PR TITLE
integrated google analytics

### PR DESCRIPTION
**Pull request by dbarochiya**
I have added the steps to integrate google analytics, this can also be added as the separate module.

* It will prompt for creating the analytics account after the deployment
* Based on the input from the user, it will update the `trackingId` in the config.js file ( It will be used by Google to generate analytics) 
* Code change will be pushed into the master branch, which will trigger a new netlify build. 

note: I have added this package for integrating the google analytics 
           `"gatsby-plugin-google-analytics": "^2.0.20"`

### CODE REVIEW

**Comment by mathieudutour** [comment]
So I don't really want to add GA by default, way too much info gathered by Google. 
I was more thinking about just adding a document about how to add GA to the created project (pretty much the steps you wrote here).

If I were to add a default analytic service, I'd add https://simpleanalytics.io

**Comment by dbarochiya** [comment]
Even I had that concern about Google gathering the sheer amount of data. Please recommend any free alternative available for the people who are just starting into the blogging world and don't have much bandwidth to pay for analytics service

**Comment by mathieudutour** [comment]
for now I don't have any recommendation. Tbh we might be able to use netlify's functions to spin up a small analytic service. That's in my backlog of ideas somewhere.

That's why I think the best for now is to just have a doc with how to install GA and simpleanalytics, for the user to choose

**Comment by dbarochiya** [comment]
> So I don't really want to add GA by default, way too much info gathered by Google.

By the way, it will ask the user first for the permission before adding analytics, not a default option.

**Comment by paramaggarwal** [comment]
I propose that GA support is not added to the initial onboarding, but is an advanced step that people can choose to setup via a config variable. The beauty of this tool is in the simple onboarding and adding a GA step just adds one more step.

**Comment by mathieudutour** [comment]
That also look interesting: https://www.netlify.com/blog/2019/07/10/netlify-analytics---accurate-insights-without-performance-impacts

**Comment by alexfinnarn** [comment]
My two cents...since this project uses Gatsby, just link to https://www.gatsbyjs.org/docs/adding-analytics/ or provide a section in the readme with that link and one about Netlify and some more about x, y, and z. 

I do agree that analytics shouldn't be installed by default even though Medium does provide you some analytics data. To me, "owning your content" is all about taking the power away from large entities that provide free services to horde and use your data. I will add analytics to my site, but I will choose to do so rather than have some solution forced upon me.

**Comment by mathieudutour** [comment]
I think I'd like to add an easy path to support https://www.goatcounter.com/. Probably just setting the goatcounter code in the config and conditionally add the gatsby plugin (https://www.gatsbyjs.org/packages/gatsby-plugin-goatcounter) if present.

Seems like the best free indie option out there

**Pull request closed without merging**
